### ISSUE TITLE
Rebasing the testing branch be ole would not fix the not resigned the old updates that he did, which led us not being able to merge it with main   

### ISSUE THREAD

**Issue by therealstrikeman** [therealstrikeman/godot#60]
### Describe the bug

please if anyone sees this post, contact our contributors and ask one of them to talk to ole,  so we can rebase all commits which are  not signed, so we can merge with main, someday,  
-Strikeman

**Comment by OleMortensen8** [comment]
the commit should be signed by you since it's your repository and commit and only you have the signed gpg keys belonging to you I can only signed the one belonging to me because the signed commits looks for your associated signed email. **Unless they were never signed, I can't sign your commits in your name.**

**Comment by therealstrikeman** [comment]
okay shoud i sent you my key so you can verify all of them
